config/routes.rb
Rails.application.routes.draw do
  devise_for :dusers
  get '/about',  to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',  to: 'cookies#new'
  post '/login',  to: 'cookies#create'
  delete '/logout', to: 'cookies#destroy'
  root 'static_pages#home'
  resources :users, only: [:edit, :update]
  resources :courses
  resources :followments, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :old_exams
  resources :account_activations, only: [:edit]
end

app/models/old_exam.rb
class OldExam < ApplicationRecord
  has_one_attached :file
  belongs_to :course
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 50 }
  validate :file?


  private

  def file?
    errors.add(:base, 'Please upload exam pdf') unless file.attached?
    if file.attached? && !file.content_type.in?(%w(application/pdf))
      errors.add(:document, 'Must be a PDF file')
    end
  end
end

app/controllers/old_exams_controller.rb
require "google/cloud/storage"

class OldExamsController < ApplicationController
  before_action :authenticate_duser!, only: [:new, :edit, :update, :destroy]
  before_action :admin_duser!, only: [:new, :edit, :update, :destroy]

  def show
    @old_exam = OldExam.find(params[:id])
    @comments = @old_exam.comments.paginate(page: params[:page], per_page: 10)
  end

  def new
    @old_exam = OldExam.new(course_id: params[:course_id])
  end

  def create
    @old_exam = OldExam.new(user_params)
    @old_exam.file.attach(params[:old_exam][:file])

    if @old_exam.save
      flash[:success] = "Exam created!"
      redirect_to course_path(@old_exam.course_id)
    else
      render 'new'
    end
  end

  def edit
    @old_exam = OldExam.find(params[:id])
  end

  def update
    @old_exam = OldExam.find(params[:id])
    id = @old_exam.course_id
    if @old_exam.update_attributes(user_params)
      flash[:success] = "Successful edit!"
      redirect_to course_path(id)
    else
      render 'edit'
    end
  end

  def destroy
    exam = OldExam.find(params[:id])
    id = exam.course_id
    exam.destroy
    flash[:success] = "Exam deleted"
    redirect_to course_path(id)
  end


  private

  def user_params
    params.require(:old_exam).permit(:title, :course_id)
  end
end

app/helpers/old_exams_helper.rb
module OldExamsHelper
end

app/views/old_exams/_card_old_exam.html.erb
<div class="card my-3">
  <% if @old_exam.file.previewable? %>
    <%= image_tag(@old_exam.file.preview(resize: "300x300>"), class: "card-img-top") %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= @old_exam.title %> <% if @old_exam.created_at >= 1.day.ago %><span class="badge badge-secondary">New</span><% end %></h5>
    <div class="btn-group-vertical" role="group" aria-label="Old Exam Buttons">
      <%= link_to "Download", rails_blob_path(@old_exam.file, disposition: "attachment"), class: "btn btn-primary btn-md", role: "button" %>
      <%=
        link_to_unless_current "Show", old_exam_path(@old_exam.id), class: "btn btn-primary btn-md", role: "button" do
          link_to "To course", course_path(@old_exam.course.id), class: "btn btn-primary btn-md", role: "button"
        end
      %> 
      <% if current_duser.try(:admin?) %>
        <%= link_to "Update", edit_old_exam_path(@old_exam.id), class: "btn btn-secondary btn-md", role: "button" %>
        <%= link_to "Delete", old_exam_path(@old_exam.id), method: :delete, class: "btn btn-secondary btn-md", role: "button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/old_exams/_form.html.erb
<%= form_for(@old_exam) do |f| %>
  <%# prints out if anny errors in form %>
  <% if @old_exam.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-warning">
        The form contains <%= pluralize(@old_exam.errors.count, "error") %>.
      </div>
      <ul>
        <% @old_exam.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter title" %>
  </div>

  <div class="form-group">
    <%= f.label :file %>
    <%= f.file_field :file, multiple: false %>
  </div>

  <div class="form-group">
    <%= f.label :course_id %>
    <%= f.collection_select :course_id, Course.all, :id, :name %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/old_exams/edit.html.erb
<% provide(:title, 'Edit Old Exam') %>
<% provide(:button_text, 'Edit old exam') %>
<h1>Edit old exam</h1>
<%= render 'form' %>

app/views/old_exams/new.html.erb
<% provide(:title, 'New Old Exam') %>
<% provide(:button_text, 'Create old exam') %>
<h1>Create old exam</h1>
<%= render 'form' %>

app/views/old_exams/show.html.erb
<% provide(:title, 'Show Old Exam') %>
<h1><%= @old_exam.title %></h1>

<div class="row justify-content-center">

  <div class="col-md-4">

    <% if duser_signed_in? %>
      <%= form_for(current_duser.comments.build) do |f| %>
        <% if current_duser.comments.build.errors.any? %>
          bite
        <% end %>
        <div><%= f.hidden_field :old_exam_id, value: @old_exam.id %></div>
        <div class="form-group">
          <%= f.text_area :content, class: "form-control", placeholder: "Enter comment" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, multiple: false, class: "form-control-file" %>
        </div>
        <%= f.submit "Post", class: "btn btn-primary" %>
      <% end %>
    <% end %>
    
    <%= render "card_old_exam" %>

  </div>

  <div class="col-md-8">
    <% @comments.each do |comment| %>
      <div class="list-group list-group-flush">
        <div class="list-group-item">
          <h6>By <%= comment.duser.email %>
          <% if comment.duser.admin? %><span class="badge badge-info">class representative</span><% end %>
          <div class="btn-group">
            <% if current_duser.try(:admin?) %>
              <button type="button" class="btn btn-secondary dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
              <div class="dropdown-menu">
                <%= link_to "Delete", comment_path(comment.id), method: :delete, class: "dropdown-item" %>
              </div>
            <% end %>
          </div></h6>
          <div><%= comment.content %></div>
          <% if comment.image.attached? %>
            <div>
              <a href="<%= rails_blob_path(comment.image, disposition: "attachment") %>">
                <img src="<%= url_for(comment.image) %>" alt="attached image" style="width: 150px;"/>
              </a>
            </div>
          <% end %>
          <small>Posted <%= time_ago_in_words comment.created_at %> ago</small>
        </div>
      </div>
    <% end %>
    <%= will_paginate @comments, page_links: false, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>

</div>