config/routes.rb
Rails.application.routes.draw do
  devise_for :dusers
  get '/about',  to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',  to: 'cookies#new'
  post '/login',  to: 'cookies#create'
  delete '/logout', to: 'cookies#destroy'
  root 'static_pages#home'
  resources :users, only: [:edit, :update]
  resources :courses
  resources :followments, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :old_exams
  resources :account_activations, only: [:edit]
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_duser!, only: [:new, :edit, :update, :destroy]
  before_action :admin_duser!, only: [:new, :edit, :update, :destroy]

  def index
    @courses = Course.search(params[:search]).paginate(page: params[:page], per_page: 10)
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(user_params)
    if @course.save
      flash[:success] = "Course created!"
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(user_params)
      flash[:success] = "Successful edit!"
      redirect_to courses_path
    else
      render 'edit'
    end
  end

  def destroy
    Course.find(params[:id]).destroy
    flash[:success] = "Course deleted"
    redirect_to courses_path
  end


  private

  def user_params
    params.require(:course).permit(:name, :description)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course_list.html.erb
<div class="accordion" id="accordionCourses">
  <% @courses.each do |course| %>
    <% @course = course %>
    <div class="card">
      <div class="card-header" id="heading<%= course.id %>">
        <h5 class="mb-0">
          <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse<%= course.id %>" aria-expanded="true" aria-controls="collapse<%= course.id %>">
            <%= course.name %>
          </button>
        </h5>
      </div>

      <div id="collapse<%= course.id %>" class="collapse" aria-labelledby="heading<%= course.id %>" data-parent="#accordionCourses">
        <div class="card-body">
          <p class="card-text"><%= course.description %></p>

          <div class="btn-toolbar" role="toolbar" aria-label="Toolbar courses">

            <div class="btn-group mr-2" role="group" aria-label="First group">
              <%= render 'courses/follow_form' if duser_signed_in? %>
            </div>

            <div class="btn-group mr-2" role="group" aria-label="Second group">
              <%= link_to "Show", course_path(@course.id), class: "btn btn-primary" %>
              <% if current_duser.try(:admin?) and current_page?(controller: 'courses') %>
                <%= link_to "Update", edit_course_path(course.id), class: "btn btn-secondary" %>
                <%= link_to "Delete", course_path(course.id), method: :delete, data: { confirm: "You sure?" }, class: "btn btn-secondary" %>
              <% end %>
            </div>

          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @courses, page_links: false, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/courses/_follow.html.erb
<%= form_for(current_duser.followments.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :course_id, @course.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/courses/_follow_form.html.erb
<div id="<%= "follow_form_#{@course.id}" %>">
  <% if current_duser.courses.exists?(@course.id) %>
    <%= render 'courses/unfollow' %>
  <% else %>
    <%= render 'courses/follow' %>
  <% end %>
</div>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <%# prints out if anny errors in form %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-warning">
        The form contains <%= pluralize(@course.errors.count, "error") %>.
      </div>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter description" %>
  </div>
  
  <div class="form-group">
    <%= f.label :group_id %>
    <%= f.collection_select :group_id, Group.all, :id, :name %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/courses/_unfollow.html.erb
<%= form_for(current_duser.followments.find_by(course_id: @course.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/courses/edit.html.erb
<% provide(:title, 'Edit Course') %>
<% provide(:button_text, 'Edit course') %>
<h1>Edit course</h1>
<%= render 'form' %>

app/views/courses/index.html.erb
<% provide(:title, "List Courses") %>
<h1>List of available courses</h1>

<%= form_tag(courses_path, method: "get", class: "form-inline my-2 my-lg-0") do %>
  <%= text_field_tag :search, nil, class: "form-control mr-sm-2", type: "search", placeholder: "Search" %>
  <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>

<%= render 'course_list' %>

<% if current_duser.try(:admin?) %>
  <%= link_to "Create new course", new_course_path, class: "btn btn-primary btn-md", role: "button" %>
<% end %>

app/views/courses/new.html.erb
<% provide(:title, "New Courses") %>
<% provide(:button_text, 'Create course') %>
<h1>Create a new course</h1>
<%= render 'form' %>

app/views/courses/show.html.erb
<% provide(:title, "Show Courses") %>
<h1><%= @course.name %></h1>
<div class="card-deck">
  <% @course.old_exams.each do |exam| %>
    <% @old_exam = exam %>
    <%= render 'old_exams/card_old_exam' %>
  <% end %>
</div>

<% if current_duser.try(:admin?) %>
  <%= link_to "Add new exam", new_old_exam_path(course_id: @course.id), class: "btn btn-primary btn-md", role: "button" %>
<% end %>