config/routes.rb
Rails.application.routes.draw do
  devise_for :dusers
  get '/about',  to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',  to: 'cookies#new'
  post '/login',  to: 'cookies#create'
  delete '/logout', to: 'cookies#destroy'
  root 'static_pages#home'
  resources :users, only: [:edit, :update]
  resources :courses
  resources :followments, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :old_exams
  resources :account_activations, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image
  belongs_to :duser
  belongs_to :old_exam

  validates :content, presence: true, length: { maximum: 255 }
  validate :image?


  private

  def image?
    if image.attached? && !image.content_type.in?(%w(image/jpeg))
      errors.add(:document, 'Must be a jpg image')
    end
  end
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :followments, dependent: :destroy
  has_many :dusers, through: :followments
  has_many :old_exams, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 255 }

  def Course.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/duser.rb
class Duser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followments
  has_many :courses, through: :followments
  has_many :comments
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :course
end

app/models/followment.rb
class Followment < ApplicationRecord
  belongs_to :duser
  belongs_to :course
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :courses

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/old_exam.rb
class OldExam < ApplicationRecord
  has_one_attached :file
  belongs_to :course
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 50 }
  validate :file?


  private

  def file?
    errors.add(:base, 'Please upload exam pdf') unless file.attached?
    if file.attached? && !file.content_type.in?(%w(application/pdf))
      errors.add(:document, 'Must be a PDF file')
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_duser!
  before_action :admin_duser!, only: :destroy

  def create
    @comment = current_duser.comments.build(user_params)
    if @comment.save
      flash[:success] = "Comment created!"
      redirect_to old_exam_path(@comment.old_exam_id)
    else
      flash[:danger] = "ERROR!"
      redirect_to old_exam_path(@comment.old_exam_id)
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    id = comment.old_exam.id
    comment.destroy
    flash[:success] = "Comment deleted"
    redirect_to old_exam_path(id)
  end


  private

  def user_params
    params.require(:comment).permit(:content, :old_exam_id, :image)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_duser!, only: [:new, :edit, :update, :destroy]
  before_action :admin_duser!, only: [:new, :edit, :update, :destroy]

  def index
    @courses = Course.search(params[:search]).paginate(page: params[:page], per_page: 10)
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(user_params)
    if @course.save
      flash[:success] = "Course created!"
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(user_params)
      flash[:success] = "Successful edit!"
      redirect_to courses_path
    else
      render 'edit'
    end
  end

  def destroy
    Course.find(params[:id]).destroy
    flash[:success] = "Course deleted"
    redirect_to courses_path
  end


  private

  def user_params
    params.require(:course).permit(:name, :description)
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:course_id, :file, :date)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user, only: [:new, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :edit, :update, :destroy]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(user_params)
    if @group.save
      flash[:success] = "Course created!"
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(user_params)
      flash[:success] = "Successful edit!"
      redirect_to groups_path
    else
      render 'edit'
    end
  end


  private

  def user_params
    params.require(:group).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/followments_helper.rb
module FollowmentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/old_exams_helper.rb
module OldExamsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MenexaTech | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <%= link_to "MenexaTech", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Courses", courses_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <% if !duser_signed_in? %>
            <li class="nav-item">
              <%= link_to "Login", new_duser_session_path, class: "nav-link" %>
            </li>
          <% end %>

          <% if duser_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Logged in as <%= current_duser.email %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit profile", edit_duser_registration_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Logout", destroy_duser_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>

        </ul>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <%# TODO: come up with a better way to do this %>
        <% if message_type == "notice" %>
          <% message_type = "primary" %>
        <% elsif message_type == "alert" %>
          <% message_type = "warning" %>
        <% elsif message_type == "success" %>
          <% message_type = "success" %>
        <% elsif message_type == "alert" %>
          <% message_type = "danger" %>
        <% end %>

        <div class="<%= "alert alert-#{message_type}" %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>